version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - yum install -y python3-pip
      - pip3 install ansible
      - ansible-galaxy collection install community.aws
      - ansible-galaxy collection install amazon.aws:==3.3.1 --force
      - ansible-galaxy collection install amazon.aws

  build:
    commands:
      - ansible-playbook -i localhost appspec.yml -v

artifacts:
  files: '**/*'
